- name: Configure machine (Universal DevSecOps Base)
  hosts: local
  connection: local
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: ['common', 'base']

    - role: security
      tags: ['security', 'base']

    - role: desktop
      tags: ['desktop', 'workstation']

    - role: dotfiles
      tags: ['dotfiles']
